//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutPlaner.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkoutPlaner.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felvett gyakorlatok.
        /// </summary>
        public static string AddedExercises {
            get {
                return ResourceManager.GetString("AddedExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyakorlatok hozzáadása.
        /// </summary>
        public static string AddExercises {
            get {
                return ResourceManager.GetString("AddExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új edzés hozzáadása.
        /// </summary>
        public static string AddWorkout {
            get {
                return ResourceManager.GetString("AddWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkar.
        /// </summary>
        public static string Alkar {
            get {
                return ResourceManager.GetString("Alkar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatikus szinkronizáció bekapcsolása.
        /// </summary>
        public static string AutSync {
            get {
                return ResourceManager.GetString("AutSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hát.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicepsz.
        /// </summary>
        public static string Bicepsz {
            get {
                return ResourceManager.GetString("Bicepsz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mell.
        /// </summary>
        public static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérlek válassz!.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérlek add meg a dátumot!.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combizom.
        /// </summary>
        public static string Combizom {
            get {
                return ResourceManager.GetString("Combizom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teljesítési idő.
        /// </summary>
        public static string CompleteTime {
            get {
                return ResourceManager.GetString("CompleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulálok, teljesítetted az edzést!.
        /// </summary>
        public static string Congrats {
            get {
                return ResourceManager.GetString("Congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba a hálózati kapcsolat során..
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új edzésterv létrehozása.
        /// </summary>
        public static string CreateNewWorkout {
            get {
                return ResourceManager.GetString("CreateNewWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nehézség.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pelda@gmail.com.
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájl helye:.
        /// </summary>
        public static string FilePlace {
            get {
                return ResourceManager.GetString("FilePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasizom.
        /// </summary>
        public static string Hasizom {
            get {
                return ResourceManager.GetString("Hasizom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hátizom.
        /// </summary>
        public static string Hátizom {
            get {
                return ResourceManager.GetString("Hátizom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utolsó bejelentkezés.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utolsó sikeres szinkronizáció időpontja.
        /// </summary>
        public static string LastSuccesfulSync {
            get {
                return ResourceManager.GetString("LastSuccesfulSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Láb.
        /// </summary>
        public static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mellizom.
        /// </summary>
        public static string Mellizom {
            get {
                return ResourceManager.GetString("Mellizom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzenet.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovább.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs kamera.
        /// </summary>
        public static string NoCam {
            get {
                return ResourceManager.GetString("NoCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem elérhető a kamera..
        /// </summary>
        public static string NoCamerAvailable {
            get {
                return ResourceManager.GetString("NoCamerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem elérhető az internet..
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs egy elem se a listában..
        /// </summary>
        public static string NoItem {
            get {
                return ResourceManager.GetString("NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az elem nem törölhető, mert másik elem kapcsolódik hozzá..
        /// </summary>
        public static string NotDeleteableWorkout {
            get {
                return ResourceManager.GetString("NotDeleteableWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Még egyetlen felhasználó se jelentkezett be az alkalmazásba..
        /// </summary>
        public static string NoUserMessage {
            get {
                return ResourceManager.GetString("NoUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs felhasználó.
        /// </summary>
        public static string NoUserTitle {
            get {
                return ResourceManager.GetString("NoUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenleg egy edzés sem elérhető..
        /// </summary>
        public static string NoWorkoutAdded {
            get {
                return ResourceManager.GetString("NoWorkoutAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline mód.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oké.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellenörző jelszó.
        /// </summary>
        public static string PasswordAgain {
            get {
                return ResourceManager.GetString("PasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValaMiN@12.
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szünet.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismétlés szám.
        /// </summary>
        public static string Reps {
            get {
                return ResourceManager.GetString("Reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valami hiba történt a fájl mentése során..
        /// </summary>
        public static string SaveFileError {
            get {
                return ResourceManager.GetString("SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés a naptárba.
        /// </summary>
        public static string SaveToCalendar {
            get {
                return ResourceManager.GetString("SaveToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorozatszám.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indít.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezd el most!.
        /// </summary>
        public static string StartNewWorkout {
            get {
                return ResourceManager.GetString("StartNewWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Állj!.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha megállítja az edzést, azzal törlődik az eredmény..
        /// </summary>
        public static string StopMessage {
            get {
                return ResourceManager.GetString("StopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres szinkronizáció..
        /// </summary>
        public static string SuccesfullSync {
            get {
                return ResourceManager.GetString("SuccesfullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres törlés..
        /// </summary>
        public static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres kijelentkezés..
        /// </summary>
        public static string SuccessLogout {
            get {
                return ResourceManager.GetString("SuccessLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos törli?.
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szinkronizációs statisztika.
        /// </summary>
        public static string SyncTitle {
            get {
                return ResourceManager.GetString("SyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASDD.
        /// </summary>
        public static string Teszt {
            get {
                return ResourceManager.GetString("Teszt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időpont.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törzsizomzat.
        /// </summary>
        public static string Törzsizomzat {
            get {
                return ResourceManager.GetString("Törzsizomzat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricepsz.
        /// </summary>
        public static string Tricepsz {
            get {
                return ResourceManager.GetString("Tricepsz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vádli.
        /// </summary>
        public static string Vádli {
            get {
                return ResourceManager.GetString("Vádli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vállizom.
        /// </summary>
        public static string Vállizom {
            get {
                return ResourceManager.GetString("Vállizom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figyelmeztetés!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hét.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edzés neve.
        /// </summary>
        public static string WorkoutName {
            get {
                return ResourceManager.GetString("WorkoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kemény edzés.
        /// </summary>
        public static string WorkoutNamePlaceHolder {
            get {
                return ResourceManager.GetString("WorkoutNamePlaceHolder", resourceCulture);
            }
        }
    }
}
